# Generated by Django 5.1.3 on 2024-12-06 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyreport',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.userprofile'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.userprofile'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='override_calorie_goal',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
